#!/bin/sh
HERE=$(dirname "$0")
python $HERE/import-feeds.py
python $HERE/render.py $HERE/templates/config.ini > $HERE/out/config.ini

rsync $HERE/out/config.ini iron-blogger@ratchet.noisebridge.systems:~/planet/config.ini

python $HERE/update-participants.py
